app/views/auth.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for)
from werkzeug.security import check_password_hash, generate_password_hash
from app.db.db import get_db, close_db
import os

# Création d'un blueprint contenant les routes ayant le préfixe /auth/...
auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

# Route /auth/register
@auth_bp.route('/register', methods=('GET', 'POST'))
def register():

    # Si des données de formulaire sont envoyées vers la route /register (ce qui est le cas lorsque le formulaire d'inscription est envoyé)
    if request.method == 'POST':

        # On récupère les champs 'username' et 'password' de la requête HTTP
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        name = request.form['name']
        last_name = request.form['last_name']
        # On récupère la base de donnée
        db = get_db()

        # Si le nom d'utilisateur et le mot de passe ont bien une valeur
        # on essaie d'insérer l'utilisateur dans la base de données
        if username and password:
            try:
                db.execute("INSERT INTO users (username, password, email, name, last_name) VALUES (?, ?, ?, ?, ?)",(username, generate_password_hash(password), email, name, last_name))
                # db.commit() permet de valider une modification de la base de données
                db.commit()
                # On ferme la connexion à la base de données pour éviter les fuites de mémoire
                close_db()
                

            except db.IntegrityError:

                # La fonction flash dans Flask est utilisée pour stocker un message dans la session de l'utilisateur
                # dans le but de l'afficher ultérieurement, généralement sur la page suivante après une redirection
                error = f"Utilisateur {username} déjà enregistré."
                flash(error)
                return redirect(url_for("auth.register"))
            
            return redirect(url_for("auth.login"))
         
        else:
            error = "Nom d'utilisateur ou mot de passe invalide"
            flash(error)
            return redirect(url_for("auth.login"))
    else:
        # Si aucune donnée de formulaire n'est envoyée, on affiche le formulaire d'inscription
        return render_template('auth/register.html')

# Route /auth/login
@auth_bp.route('/login', methods=('GET', 'POST'))
def login():
    # Si des données de formulaire sont envoyées vers la route /login (ce qui est le cas lorsque le formulaire de login est envoyé)
    if request.method == 'POST':

        # On récupère les champs 'username' et 'password' de la requête HTTP
        username = request.form['username']
        password = request.form['password']

        # On récupère la base de données
        db = get_db()
        
        # On récupère l'utilisateur avec le username spécifié (une contrainte dans la db indique que le nom d'utilisateur est unique)
        # La virgule après username est utilisée pour créer un tuple contenant une valeur unique
        user = db.execute('SELECT * FROM users WHERE username = ?', (username,)).fetchone()

        # On ferme la connexion à la base de données pour éviter les fuites de mémoire
        close_db()

        # Si aucun utilisateur n'est trouve ou si le mot de passe est incorrect
        # on crée une variable error 
        error = None
        if user is None:
            error = "Nom d'utilisateur incorrect"
        elif not check_password_hash(user['password'], password):
            error = "Mot de passe incorrect"

        # S'il n'y pas d'erreur, on ajoute l'id de l'utilisateur dans une variable de session
        # De cette manière, à chaque requête de l'utilisateur, on pourra récupérer l'id dans le cookie session
        if error is None:
            session.clear()
            session['id_user'] = user['id_user']
            # On redirige l'utilisateur vers la page principale une fois qu'il s'est connecté
            return redirect("/")
        
        else:
            # En cas d'erreur, on ajoute l'erreur dans la session et on redirige l'utilisateur vers le formulaire de login
            flash(error)
            return redirect(url_for("auth.login"))
    else:
        return render_template('auth/login.html')

# Route /auth/logout
@auth_bp.route('/logout')
def logout():
    # Se déconnecter consiste simplement à supprimer le cookie session
    session.clear()

    # On redirige l'utilisateur vers la page principale une fois qu'il s'est déconnecté
    return redirect("/")

@auth_bp.route('/reset')
def reset():
    return render_template('auth/reset.html')


@auth_bp.route('/password_reset')
def password_reset():
    return render_template('auth/password_reset.html')



@auth_bp.route('/people')
def artists():
    return render_template('artists/people.html')

@auth_bp.route('/artworks')
def gallery():
    return render_template('gallery/artworks.html')

@auth_bp.route('/createproject')
def create():
    # Se déconnecter consiste simplement à supprimer le cookie session
    return render_template('create/createproject.html')

    # On redirige l'utilisateur vers la page principale une fois qu'il s'est déconnecté
    return redirect("/")
# Fonction automatiquement appelée à chaque requête (avant d'entrer dans la route) sur une route appartenant au blueprint 'auth_bp'
# La fonction permet d'ajouter un attribut 'user' représentant l'utilisateur connecté dans l'objet 'g' 
@auth_bp.before_app_request
def load_logged_in_user():

    # On récupère l'id de l'utilisateur stocké dans le cookie session
    id_user = session.get('id_user')

    # Si l'id de l'utilisateur dans le cookie session est nul, cela signifie que l'utilisateur n'est pas connecté
    # On met donc l'attribut 'user' de l'objet 'g' à None
    if id_user is None:
        g.user = None

    # Si l'id de l'utilisateur dans le cookie session n'est pas nul, on récupère l'utilisateur correspondant et on stocke
    # l'utilisateur comme un attribut de l'objet 'g'
    else:
         # On récupère la base de données et on récupère l'utilisateur correspondant à l'id stocké dans le cookie session
        db = get_db()
        g.user = db.execute('SELECT * FROM users WHERE id_user = ?', (id_user,)).fetchone()
        # On ferme la connexion à la base de données pour éviter les fuites de mémoire
        close_db()

app/views/home.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for)

# Routes /...
home_bp = Blueprint('home', __name__)



# Route /
@home_bp.route('/', methods=('GET', 'POST'))
def landing_page():
    # Affichage de la page principale de l'application
    return render_template('home/index.html')

# Gestionnaire d'erreur 404 pour toutes les routes inconnues
@home_bp.route('/<path:text>', methods=['GET', 'POST'])
def not_found_error(text):
    return render_template('home/404.html'), 404

app/views/user.py
from flask import (Blueprint, flash, g, redirect, render_template, request, session, url_for)
from app.utils import *

# Routes /user/...
user_bp = Blueprint('user', __name__, url_prefix='/user')

# Route /user/profile accessible uniquement à un utilisateur connecté grâce au décorateur @login_required
@user_bp.route('/profile', methods=('GET', 'POST'))
@login_required 
def show_profile():
    # Affichage de la page principale de l'application
    return render_template('user/profile.html')

@user_bp.route('/edit', methods=('GET', 'POST'))
@login_required 
def edit_profile():

    return render_template('user/edit.html')

app/templates/base.html
<!doctype html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>
    <header id="header">
        <nav id="header-nav">
            <div id="header-nav-img">
                <a href="{{url_for('home.landing_page')}}">
                    <img src="{{url_for('static', filename='imgs/logo.png')}}" alt="logo-unitearts"/>
                </a>
            </div>
            <ul id="header-nav-menu">
                    <li><a href="{{ url_for('auth.artists') }}">artistes</a></li>
                    <li><a href="{{ url_for('auth.gallery') }}">oeuvres</a></li>
                    <li><a href="{{ url_for('auth.create') }}">créer un projet</a></li>
                {% if g.user %}
                    <li><a href="{{ url_for('auth.create') }}">projets en progrès</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.register') }}">s'enregistrer</a>
                    <li><a href="{{ url_for('auth.login') }}">se connecter</a>
                {% endif %}
            </ul>
            
            <div id="header-nav-img" class="profile-pic">
                {%if g.user['profile_pic'] is none%}
                    <a href="{{url_for('user.show_profile')}}">
                        <img class="round" src="/static/imgs/profile-pic.webp" alt="default profile pic">
                    </a>
                {% else %}
                    <a href="{{url_for('user.show_profile')}}">
                        <span  >{{g.user['profile_pic']}}</span>
                    </a>
                {% endif %}
            </div>
        </nav>
            <hr class="line">
    </header>
        
    <main id="main-content">
        {% block content %}{% endblock %}
    </main>

    <footer id="footer">
        <hr class="line2">
        <div id="footer-nav">
            <div>
                <p>Template de base TM</p>
            </div>
            <div>
                <p>UniteArts</p>
            </div>
            <div>
                <p>Simon Buenaventura</p>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
</body>